apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: burrito-server
  {{- with mergeOverwrite (deepCopy .Values.global.metadata) .Values.server.metadata }}
  labels:
    {{- toYaml .labels | nindent 4}}
  annotations:
    {{- toYaml .annotations | nindent 4}}
  {{- end }}
rules:
{{- include "burrito.serverRules" . | nindent 0 }}
